app:
    production: false
    environment: 'DEV'
    version: '1.0.0'
    urlIntranetLogin: http://mejico.isban.dev.corp/LOGMEX_ENS/BtoChannelDriver.bto?dse_operationName=loginMEX
    urlAsuntos: https://gsrh-gateway-service-mx-golden-source-tdb-dev.appls.mex01.mex.dev.mx1.paas.cloudcenter.corp/gsrh
    urlAutoAyuda: https://gsrh-gateway-service-mx-golden-source-tdb-dev.appls.mex01.mex.dev.mx1.paas.cloudcenter.corp/gsrh
    urlBusqueda: https://gsrh-gateway-service-mx-golden-source-tdb-dev.appls.mex01.mex.dev.mx1.paas.cloudcenter.corp/gsrh
    urlCategorias: https://gsrh-gateway-service-mx-golden-source-tdb-dev.appls.mex01.mex.dev.mx1.paas.cloudcenter.corp/gsrh
    urlCentros: https://gsrh-gateway-service-mx-golden-source-tdb-dev.appls.mex01.mex.dev.mx1.paas.cloudcenter.corp/gsrh
    urlPerfil: https://gsrh-gateway-service-mx-golden-source-tdb-dev.appls.mex01.mex.dev.mx1.paas.cloudcenter.corp/perfilamiento
    urlSantec: https://gsrh-gateway-service-mx-golden-source-tdb-dev.appls.mex01.mex.dev.mx1.paas.cloudcenter.corp/autenticacion
    applicationName: INTRAMX-APPEB-SSO_GOLDEN_SOURCE
    cookieName: cookie_INTRAMX-APPEB-SSO_GOLDEN_SOURCE
    headerTokenName: cookie-aplicativa